# Generated by Django 5.1.4 on 2025-03-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Route endommagée', 'Route endommagée'), ("Coupure d'eau", "Coupure d'eau"), ("Problème d'électricité", "Problème d'électricité"), ('autre', 'Autre')], max_length=50, null=True)),
                ('Localiter', models.CharField(choices=[('Dakar', 'Dakar'), ('Thies', 'Thies'), ('Mbour', 'Mbour'), ('Saint-louis', 'Saint-louis'), ('Sedhiou', 'Sedhiou'), ('Tambacounda', 'Tambacounda'), ('Louga', 'Louga')], max_length=40)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Résolue', 'Résolue')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
