# Generated by Django 5.1.7 on 2025-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Résolue', 'Résolue')], default='En attente', max_length=20),
        ),
    ]
