# Generated by Django 5.1.7 on 2025-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0002_alter_plainte_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
