# Generated by Django 5.1.7 on 2025-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0003_plainte_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='categorie',
            field=models.CharField(choices=[('Route endommagée', 'Route endommagée'), ("Coupure d'eau", "Coupure d'eau"), ("Problème d'électricité", "Problème d'électricité"), ('autre', 'Autre')], max_length=50, null=True),
        ),
    ]
